const SHOP_DATA = [
    {
        id: 1,
        title: "Hats",
        routeName: "hats",
        items: [
            {
                id: 1,
                name: "Brown Brim",
                imageUrl: "/images/items/(121).jpg",
                price: 25,
            },
            {
                id: 2,
                name: "Someiallo",
                imageUrl: "/images/items/(122).jpg",
                price: 25,
            },
            {
                id: 3,
                name: "Yellow Dai",
                imageUrl: "/images/items/(123).jpg",
                price: 25,
            },
            {
                id: 4,
                name: "Sky Hat",
                imageUrl: "/images/items/(124).jpg",
                price: 25,
            },
            {
                id: 5,
                name: "Brown Brim",
                imageUrl: "/images/items/(125).jpg",
                price: 25,
            },
            {
                id: 6,
                name: "Brown Brim",
                imageUrl: "/images/items/(126).jpg",
                price: 25,
            },
            {
                id: 7,
                name: "Brown Brim",
                imageUrl: "/images/items/(127).jpg",
                price: 25,
            },
            {
                id: 8,
                name: "Brown Brim",
                imageUrl: "/images/items/(128).jpg",
                price: 25,
            },
            {
                id: 9,
                name: "Brown Brim",
                imageUrl: "/images/items/(129).jpg",
                price: 25,
            },
            {
                id: 10,
                name: "Brown Brim",
                imageUrl: "/images/items/(120).jpg",
                price: 25,
            },
        ],
    },
    {
        id: 2,
        title: "Jakets",
        routeName: "jakets",
        items: [
            {
                id: 1,
                name: "Gom Gom",
                imageUrl: "/images/items/(121).jpg",
                price: 25,
            },
            {
                id: 2,
                name: "Brown Brim",
                imageUrl: "/images/items/(122).jpg",
                price: 25,
            },
            {
                id: 3,
                name: "Brown Brim",
                imageUrl: "/images/items/(123).jpg",
                price: 25,
            },
            {
                id: 4,
                name: "Brown Brim",
                imageUrl: "/images/items/(124).jpg",
                price: 25,
            },
            {
                id: 5,
                name: "Brown Brim",
                imageUrl: "/images/items/(125).jpg",
                price: 25,
            },
            {
                id: 6,
                name: "Brown Brim",
                imageUrl: "/images/items/(126).jpg",
                price: 25,
            },
            {
                id: 7,
                name: "Brown Brim",
                imageUrl: "/images/items/(127).jpg",
                price: 25,
            },
            {
                id: 8,
                name: "Brown Brim",
                imageUrl: "/images/items/(128).jpg",
                price: 25,
            },
            {
                id: 9,
                name: "Brown Brim",
                imageUrl: "/images/items/(129).jpg",
                price: 25,
            },
            {
                id: 10,
                name: "Brown Brim",
                imageUrl: "/images/items/(120).jpg",
                price: 25,
            },
        ],
    },
    {
        id: 3,
        title: "Sneakers",
        routeName: "sneakers",
        items: [
            {
                id: 1,
                name: "Brown Brim",
                imageUrl: "/images/items/(121).jpg",
                price: 25,
            },
            {
                id: 2,
                name: "Brown Brim",
                imageUrl: "/images/items/(122).jpg",
                price: 25,
            },
            {
                id: 3,
                name: "Brown Brim",
                imageUrl: "/images/items/(123).jpg",
                price: 25,
            },
            {
                id: 4,
                name: "Brown Brim",
                imageUrl: "/images/items/(124).jpg",
                price: 25,
            },
            {
                id: 5,
                name: "Brown Brim",
                imageUrl: "/images/items/(125).jpg",
                price: 25,
            },
            {
                id: 6,
                name: "Brown Brim",
                imageUrl: "/images/items/(126).jpg",
                price: 25,
            },
            {
                id: 7,
                name: "Brown Brim",
                imageUrl: "/images/items/(127).jpg",
                price: 25,
            },
            {
                id: 8,
                name: "Brown Brim",
                imageUrl: "/images/items/(128).jpg",
                price: 25,
            },
            {
                id: 9,
                name: "Brown Brim",
                imageUrl: "/images/items/(129).jpg",
                price: 25,
            },
            {
                id: 10,
                name: "Brown Brim",
                imageUrl: "/images/items/(120).jpg",
                price: 25,
            },
        ],
    },
    {
        id: 4,
        title: "Womens",
        routeName: "womens",
        items: [
            {
                id: 1,
                name: "Brown Brim",
                imageUrl: "/images/items/(121).jpg",
                price: 25,
            },
            {
                id: 2,
                name: "Brown Brim",
                imageUrl: "/images/items/(122).jpg",
                price: 25,
            },
            {
                id: 3,
                name: "Brown Brim",
                imageUrl: "/images/items/(123).jpg",
                price: 25,
            },
            {
                id: 4,
                name: "Brown Brim",
                imageUrl: "/images/items/(124).jpg",
                price: 25,
            },
            {
                id: 5,
                name: "Brown Brim",
                imageUrl: "/images/items/(125).jpg",
                price: 25,
            },
            {
                id: 6,
                name: "Brown Brim",
                imageUrl: "/images/items/(126).jpg",
                price: 25,
            },
            {
                id: 7,
                name: "Brown Brim",
                imageUrl: "/images/items/(127).jpg",
                price: 25,
            },
            {
                id: 8,
                name: "Brown Brim",
                imageUrl: "/images/items/(128).jpg",
                price: 25,
            },
            {
                id: 9,
                name: "Brown Brim",
                imageUrl: "/images/items/(129).jpg",
                price: 25,
            },
            {
                id: 10,
                name: "Brown Brim",
                imageUrl: "/images/items/(120).jpg",
                price: 25,
            },
        ],
    },
    {
        id: 5,
        title: "Mens",
        routeName: "mens",
        items: [
            {
                id: 1,
                name: "Brown Brim",
                imageUrl: "/images/items/(121).jpg",
                price: 25,
            },
            {
                id: 2,
                name: "Brown Brim",
                imageUrl: "/images/items/(122).jpg",
                price: 25,
            },
            {
                id: 3,
                name: "Brown Brim",
                imageUrl: "/images/items/(123).jpg",
                price: 25,
            },
            {
                id: 4,
                name: "Brown Brim",
                imageUrl: "/images/items/(124).jpg",
                price: 25,
            },
            {
                id: 5,
                name: "Brown Brim",
                imageUrl: "/images/items/(125).jpg",
                price: 25,
            },
            {
                id: 6,
                name: "Brown Brim",
                imageUrl: "/images/items/(126).jpg",
                price: 25,
            },
            {
                id: 7,
                name: "Brown Brim",
                imageUrl: "/images/items/(127).jpg",
                price: 25,
            },
            {
                id: 8,
                name: "Brown Brim",
                imageUrl: "/images/items/(128).jpg",
                price: 25,
            },
            {
                id: 9,
                name: "Brown Brim",
                imageUrl: "/images/items/(129).jpg",
                price: 25,
            },
            {
                id: 10,
                name: "Brown Brim",
                imageUrl: "/images/items/(120).jpg",
                price: 25,
            },
        ],
    },
];

export default SHOP_DATA;